---
title: "Activities"
author: "André Luiz Cunha"
date: "5/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tibble)
library(dplyr)
```

# Orientados

## Pós-graduação

```{r pos}

df <- tribble(
  ~id, ~name, ~level, ~start, ~end, ~title,
  "10854033", "Helena Stein Stefani", "mestrado", "1/3/2018", "em andamento", 
    "Método de previsão de fluxo de tráfego em rodovias urbanas a partir de dados de velocidade de fontes online",
  
  "11359262", "Paola Yumi Matsumoto", "mestrado", "27/2/2019", "em andamento", 
    "Calibração de Modelo Cellular Automata para Simulação do Comportamento do Tráfego Veicular em Rodovias Paulistas",
  
  "7595421", "Andre Borgato Morelli", "doutorado", "2/3/2020", "em andamento", 
    "Investigação de eficiência e resiliência em sistemas autônomos de veículos compartilhados: uma abordagem morfológica",
  
  "9055915", "Elaine Rodrigues Ribeiro", "doutorado", "14/7/2020", "em andamento", 
    "Método para obtenção e análise de dados de comportamento do motociclista na corrente de tráfego",
  
  "5450141", "Leandro Arab Marcomini", "doutorado", "26/2/2019", "em andamento", 
    "Proposta de elaboração de um métod de detecção e classificação de eixos de caminhões baseado em imagens de vídeo"
  
)

knitr::kable(df, caption = "Orientados de pós-graduação")

```


## Graduação

```{r grad}

df <- tribble(
  ~id, ~name, ~level, ~start, ~end, ~title,
   7030024, "Helena Tanoue Vizioli", "TCC-1", "3/5/2021", "em andamento", 
    "Implementação de controle de velociade limite variável na Rodovia dos Bandeirantes",
  
  10311743, "Henrique Luiz Shibata Gino", "TCC-1", "10/5/2021", "em andamento", 
    "Proposta de modelo operacional para viagens de ônibus intermunicipais durante a pandemia da COVID-19",
  
  10311444, "Eraldo Dias de Castro Neto", "TCC-1", "10/5/2021", "em andamento", 
    "Projeto de ciclovia energeticamente confortável ao usuário para a cidade de São Carlos",
  
  9866614, "Láisla Beatriz de Carvalho Penido", "TCC-1", "10/5/2021", "em andamento", 
    "Análise de viabilidade da implementação de um sistema de parcel locker na cidade de Campinas/SP",
  
  9314198, "Pedro Victor Alves Barbosa", "Estágio", "15/2/2021", "em andamento", 
    "McKinsey & Company, Inc. do Brasil Consultoria Ltda",
  
  10311444, "Eraldo Dias de Castro Neto", "Estágio", "3/3/2021", "em andamento", 
    "HB12 SPE Empreendimentos Imobiliários Ltda",
  
  9003462, "Isabela Sarkis Cardoso", "Estágio", "4/1/2021", "em andamento",
  "B2W Companhia Digital",
  
  10311830, "Edmar Pereira dos Santos Filho", "Estágio", "19/1/2021", "em andamento",
  "RUMO Malha Norte Filial São Paulo"
)
df$start <- as.Date(df$start, format = "%d/%m/%Y")

knitr::kable(df %>% arrange(level, name), caption = "Orientados de graduação")

```